Use UCI ML Repository to get data-sets for training models

* Classification: predicts a category (e.g. winner of a football match)
* Regression: predicts a continuous outcome, a real value (salary of an employee or next day's temperature)
* Clustering: Unsupervised learning (identifying clusters of data within a high-dimensional dataset)

# Artificial Neural Network (ANN) - Regression

The dataset contains 9568 data points collected from a Combined Cycle Power Plant over 6 years (2006-2011), when the power plant was set to work with full load. Features consist of hourly average ambient variables Temperature (T), Ambient Pressure (AP), Relative Humidity (RH) and Exhaust Vacuum (V) to predict the net hourly electrical energy output (EP) of the plant.

Our aim is to predict the net hourly electrical energy output of the plant using an ANN regression model

https://archive.ics.uci.edu/ml/datasets/Combined+Cycle+Power+Plant#

## Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__ # checking tensorflow version

'2.6.0'

## Part 1: Data Preprocessing

### Importing the dataset




NN or ML models require creation of two separate subsets:

**a. Matrix Features** - subset of data containing all features (independent varibles). In this case Temperature, Ambient Pressure, Relative Humidity and Exhaust Vacuum

**b. Dependent variable vector** - one single variable which we want to predict. In this case the net hourly electrical energy output

In [4]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
x = dataset.iloc[:, :-1].values # second colon specifies a range. A range in python includes lower bound but excludes upper bound
y = dataset.iloc[:, -1].values

In [7]:
print(x)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into Training Set and Test set

In [8]:
from sklearn.model_selection import train_test_split 
# this function takes input as subsets and NOT dataframe. So we need 4 variables
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0) 
# choosing 20% observations in test set. 
# random_state fixes the randomness of training-test split. It is not cumpulsory to use random_state


## Part 2: Building the ANN

### Initialising the ANN
as a sequence of layers. The other type of ANN is a computational graph

Creating an object of sequential class using tensorflow

In [10]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer
the layers are added as an object of Dense class (class names always start with a capital letter). Dense class exists in layers in keras library, which is in turn part of tensorflow.

It is called Dense because the input layer and hidden layer neurons have full connection

We do not need to add units for the inputs as they are automatically recognised. However, we do need to add neuron units for the hidden layer, as well as the type of activation function we wish to use (here 6). Here we use the rectifier (relu) activation function, which fires up after a certain limit is reached

In [11]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second hidden layer
the method to do this is exactly the same as above. A Neural Network becomes 'Deep' when there is more than one hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the Output layer
**Sigmoid (for two categories) and Softmax (for more than two categories) activation functions for the output layer are generally used in ANN Classification algorithms. It is better to leave the activation field in Regression algorithms as default**

In [15]:
ann.add(tf.keras.layers.Dense(units = 1))

## Part 3: Training the ANN

### Compiling the ANN
connecting the ANN to an optimiser which reduces the loss during backward propagation, stochastic gradient descent. And choosing the Loss function

Adam is the most popular optimiser, and can be used for both Regression and Classification

Loss used here mean-squared-error (or root-means-squared-error) as in any Regression task. Mean-squared-error here is the sum of squared differences between the predictions and real energy outputs in the batch

In [16]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [17]:
ann.fit(x = x_train, y = y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 4598.4683
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 155.5544
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 149.4714
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 142.1018
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 133.2745
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 123.9462
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 115.0486
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 105.1524
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 95.7043
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 86.6233
Epoch 11/100
240/240 [==============================] - 0s 2ms/step - loss: 78.6361
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - loss: 

### Predicting results of the Test set

In [25]:
y_pred = ann.predict(x_test) # saving predictions to a vector y_pred to compare with actual y_test values
np.set_printoptions(precision = 2) # using numpy changing to two figured after decimal point 
# changing y_pred and y_test vectors from horizontal to vertical
# concatening the vectors vertically for side-by-side comparison. 1 --> vertical, 0 --> horizontal
print(np.concatenate((y_pred.reshape(len(y_pred),1) , y_test.reshape(len(y_test),1)), 1))

[[432.03 431.23]
 [463.15 460.01]
 [466.64 461.14]
 ...
 [473.93 473.26]
 [440.6  438.  ]
 [459.88 463.28]]


As we can see our ANN performed well and predicted values are really close to actual values